### ISSUE TITLE
As an Economic Model Application Administrator, I want to be able to get in contact with users of the application to make sure the system is being used correctly, and help users if necessary.

### ISSUE THREAD

**Issue by davidarida7** [dchudy3/Emory#16]
## Tasks

- [x] Admin can access contact information of users 

- [x] Add monitoring so that admins can contact users if they see an issue arise (optional) // This isn't something our users asked for our prioritized - is this necessary?

## Acceptance Criteria
Scenario 1: Verify consent for research study
Given: The user’s data can be used in a global study and the user needs to give consent
When:  The administrator selects the user in the system 
Then:  The user's contact information is displayed to the administrator and the administrator can contact them (via email)

Scenario 2: Verify legitimacy of user’s data.
Given: The user's data looks improbable or unlikely, the administrator wishes to contact a user to verify the data gathering technique will produce accurate results.
When:  The administrator selects the user in the system 
Then:  The user's contact information is displayed to the administrator and the administrator can contact them (via email)

Scenario 3: supply user with additional information
Given:  The user is unclear of how to collect metrics and needs assistance
When:  The administrator selects the user in the system 
Then:  The user's contact information is displayed to the administrator and the administrator can contact them (via email)

## Done Done Criteria
For our "done done criteria", please see this link: https://github.com/dchudy3/Emory/wiki/Done-Done-Criteria.

**Comment by aabedi** [comment]
First two Accepatance Criteria scenarios don't align with this user story. Consenting to a research study involves IRB approval, which is not trivial - requires an approval process, and loads of paperwork. Do we need this at all in the app itself?

**Comment by theethanbyrd** [comment]
The other two the same logic applies to the first one
